In [31]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 

## Real answer is that the matmethatical model : y = x * 2 + 2
xs : np.array = np.array([1.0, 2.0, 3.0,4.0, 5.0, 6.0], dtype=np.float)
ys : np.array = np.array([4.0, 6.0, 8.0, 10.0, 12.0, 14.0], dtype=np.float)

model : tf.keras.Sequential = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer = tf.keras.optimizers.SGD(), loss=tf.keras.losses.MeanSquaredError())
#model.fit(xs,ys, epochs=150)


#print(model.predict([10.0]))

#************************************************************************** Multiple Layer Perceptron ( Binary Classification )  ********************************************

df : pd.DataFrame = pd.read_csv("citrus.csv")


print(df.info())
print(df.head(3))
model : tf.keras.Sequential = tf.keras.Sequential([
           keras.layers.Dense(units=1, input_shape=[1]),
           keras.layers.Dense(units=8),
           keras.layers.Dense(units=1) ]
)

df["name"][df["name"] == "orange"] = 0
df["name"][df["name"] == "grapefruit"] = 1

print("\n",df["name"].unique())

#### Convert it to np.arr < Because it sucks with dataframe >
dataset : np.array = df.values
############# Only take the feature & label #######################
X : np.array = dataset[:, 1:]
Y : np.array = dataset[:, 0]
print("X values :", X)
print("Y Values : ",Y[:5])
#######################################################################


############# Normalisasi #######################
min_max_scaler_obj : preprocessing.MinMaxScaler = preprocessing.MinMaxScaler()
x_normalized :  np.array = min_max_scaler_obj.fit_transform(X)
print("Normalized %s " %(x_normalized[1:5]))
#######################################################################

############# Split Dataset #######################
x_train,x_test,y_train,y_test = train_test_split(x_normalized, Y, test_size=0.3,random_state=0 )

y_train = y_train.astype(np.float32)
y_test = y_test.astype(np.float32)

#######################################################################

############ Modelling #######################
neuron_1 : int = 32
neuron_2 : int = 1

model : tf.keras.Sequential = tf.keras.Sequential([
    keras.layers.Dense(neuron_1, 
                       activation=keras.activations.relu,
                       input_shape=(x_normalized.shape[1], )), # (5,)
    keras.layers.Dense(neuron_1,
                       activation=keras.activations.relu),
    keras.layers.Dense(neuron_2,
                       activation=keras.activations.sigmoid)
],name="Model_Ampas")

#######################################################################

############ Compilling #######################
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.SGD(),
    metrics=[
    tf.keras.metrics.BinaryAccuracy()
    ]
)
#history = model.fit(x_train, y_train,epochs=100)
#print(history)
#model.evaluate(x_test,y_test)
# [Loss, Acc]
#######################################################################






<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB
None
     name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2

 [0 1]
X values : [[2.96 86.76 172 85 2]
 [3.91 88.05 166 78 3]
 [4.42 95.17 156 81 2]
 ...
 [15.59 256.5 168 82 20]
 [15.92 260.14 142 72 11]
 [16.45 261.51 152 74 2]]
Y Values :  [0 0 0 0 0]
Normalized [[0.07042254 0.00738197 0.66233766 0.55294118 0.01851852]
 [0.10822832 0.04812589 0.53246753 0.58823529 0.        ]
 [0.111

C:\Users\User\AppData\Local\Temp\ipykernel_8260\1238132912.py:9: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  xs : np.array = np.array([1.0, 2.0, 3.0,4.0, 5.0, 6.0], dtype=np.float)
C:\Users\User\AppData\Local\Temp\ipykernel_8260\1238132912.py:10: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ys : np.array = np.array([4.0, 6.0, 8.0, 10.0

219/219 [==============================] - 1s 833us/step - loss: 0.6808 - binary_accuracy: 0.6166
Epoch 2/100
219/219 [==============================] - 0s 819us/step - loss: 0.6464 - binary_accuracy: 0.8113
Epoch 3/100
219/219 [==============================] - 0s 897us/step - loss: 0.5960 - binary_accuracy: 0.8980
Epoch 4/100
219/219 [==============================] - 0s 819us/step - loss: 0.5203 - binary_accuracy: 0.9157
Epoch 5/100
219/219 [==============================] - 0s 805us/step - loss: 0.4200 - binary_accuracy: 0.9217
Epoch 6/100
219/219 [==============================] - 0s 819us/step - loss: 0.3308 - binary_accuracy: 0.9249
Epoch 7/100
219/219 [==============================] - 0s 888us/step - loss: 0.2712 - binary_accuracy: 0.9250
Epoch 8/100
219/219 [==============================] - 0s 814us/step - loss: 0.2357 - binary_accuracy: 0.9263
Epoch 9/100
219/219 [==============================] - 0s 874us/step - loss: 0.2150 - binary_accuracy: 0.9286
Epoch 10/100
219/219 [

In [49]:

#************************************************************************** Multiple Layer Perceptron ( Multiple classes Classification )  ********************************************


import pandas as pd
import tensorflow as tf
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from tensorflow import keras



######################Preprocessing Basic Bruh################

df : pd.DataFrame = pd.read_csv("Iris.csv")
print(df.info())

df : pd.DataFrame = df.drop("Id",axis=1)

category : pd.DataFrame = pd.get_dummies(df["Species"])

df_new : pd.DataFrame = pd.concat([df, category], axis=1)
df_new = df_new.drop("Species", axis=1)
print(df_new)

####################### Convert to np and then go to the Normalization more !###########################

np_data : np.array = df_new.values
X = np_data[:, :4]
Y = np_data[:, 4:] # Col 5,6,7

# Normalizing
min_max_scale : preprocessing.MinMaxScaler =  preprocessing.MinMaxScaler() # Information of Transformation is in here !
x_normalized : np.array = min_max_scale.fit_transform(X)
print(x_normalized.shape)


## SPLIT the dataset

x_train,x_test,y_train,y_test = train_test_split(x_normalized, Y, test_size=0.3, random_state=1)

#######################################################################

####################### Modelling   ###########################
neuron_1 : int = 64
neuron_2 : int = 3 # Representing the output class
model : tf.keras.Sequential = tf.keras.Sequential([
        tf.keras.layers.Dense(units=neuron_1, activation=tf.keras.activations.relu, input_shape=(x_normalized.shape[1],)), #(4,)
        tf.keras.layers.Dense(units=neuron_1, activation=tf.keras.activations.relu),
        tf.keras.layers.Dense(units=neuron_2, activation=tf.keras.activations.softmax)
        
])

model.compile(
    loss=tf.keras.losses.CategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001),
    metrics=[
        tf.keras.metrics.CategoricalAccuracy()
    ]
)
hist = model.fit(x_train,y_train, epochs=100)
model.evaluate(x_test,y_test)
#######################################################################


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
0              5.1           3.5            1.4           0.2            1   
1              4.9           3.0            1.4           0.2            1   
2              4.7           3.2            1.3           0.2            1   
3              4.6           3.1            1.5           0.2            1   
4              5.0           3.6            1.4           0.2            1   
..       

[0.07435642927885056, 0.9777777791023254]

2/2 [==============================] - 0s 3ms/step - loss: 0.0863 - categorical_accuracy: 0.9778


[0.08628230541944504, 0.9777777791023254]